###
POST http://localhost:8080/api/rentals
Content-Type: application/json
Accept: application/json

{
  "bikeId" : "FH631",
  "userId" : "US346",
  "deliveryTime": "2022-05-24T11:20:42",
  "distance" : 2.9

}

###
GET http://localhost:8080/api/rentals?startTime=2022-05-24T17:12:50
Accept: application/json
###

