
###
GET http://localhost:8080/locations?prefix=budape/st
Accept: application/json

###
POST http://localhost:8080/locations
Content-Type: application/json
Accept: application/json

{
  "name": "Budapest",

  "lat": -10.2,
  "lon": 7.3
}

###
PUT http://localhost:8080/locations/1
Content-Type: application/json
Accept: application/json

{
  "name":"London",
  "lat": 1.2,
  "lon": 4.5
}

###
DELETE http://localhost:8080/locations/5

###
GET http://localhost:8080/locations/1567/A
Accept: application/json

### validation test
POST http://localhost:8080/locations
Content-Type: application/json
Accept: application/json

{
  "name": "",
  "lat": 1223.2,
  "lon": 121217.3
}